runners:
  emr:
    region: us-east-1
    iam_instance_profile: EMR_EC2_DefaultRole
    iam_service_role: EMR_DefaultRole
    image_version: 7.12.0
    python_bin: /usr/bin/python3.12 -u

    jobconf:
      mapreduce.map.memory.mb: 2048
      mapreduce.map.java.opts: -Xmx1536m
      mapreduce.reduce.memory.mb: 4096
      mapreduce.reduce.java.opts: -Xmx3072m
      mapreduce.job.reduce.slowstart.completedmaps: 0.9
      fs.s3a.requester-pays.enabled: "true"

    upload_dirs:
      - feed_survey

    instance_fleets:
      - InstanceFleetType: MASTER
        TargetOnDemandCapacity: 1
        InstanceTypeConfigs:
          - InstanceType: m5.xlarge
      - InstanceFleetType: CORE
        TargetOnDemandCapacity: 30
        InstanceTypeConfigs:
          - InstanceType: m5.xlarge
          - InstanceType: m5d.xlarge
          - InstanceType: r5.xlarge
          - InstanceType: r5d.xlarge
          - InstanceType: c5.xlarge
