runners:
  emr:
    region: us-east-1
    iam_instance_profile: EMR_EC2_DefaultRole
    iam_service_role: EMR_DefaultRole
    image_version: 7.12.0
    python_bin: /usr/bin/python3.12 -u
    
    bootstrap:
      - sudo dnf install -y python3.12 python3.12-pip libxml2 libxslt zlib lz4 brotli
      - aws s3 sync s3://mnot-cc-feeds/wheels/ /tmp/wheels/
      - sudo /usr/bin/python3.12 -m pip install --no-index --find-links=/tmp/wheels/ mrjob fastwarc feedparser beautifulsoup4 lxml python-dateutil requests boto3
    jobconf:
      mapreduce.map.memory.mb: 4096
      mapreduce.map.java.opts: -Xmx3072m
      mapreduce.reduce.memory.mb: 4096
      mapreduce.reduce.java.opts: -Xmx3072m
      fs.s3a.requester-pays.enabled: "true"

    upload_files:
      - cc_feeds/processor.py#processor.py
      - cc_feeds/utils.py#utils.py
      - /Users/mnot/.cache/cc-feeds/top-1m.csv#top-1m.csv

    instance_fleets:
      - InstanceFleetType: MASTER
        TargetOnDemandCapacity: 1
        InstanceTypeConfigs:
          - InstanceType: m5.xlarge
      - InstanceFleetType: CORE
        TargetSpotCapacity: 5
        InstanceTypeConfigs:
          - InstanceType: m5.xlarge
          - InstanceType: m5d.xlarge
          - InstanceType: r5.xlarge
          - InstanceType: r5d.xlarge
          - InstanceType: c5.xlarge
